# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flcore',
                'doc_host': 'https://FrLars21.github.io',
                'git_url': 'https://github.com/FrLars21/flcore',
                'lib_path': 'flcore'},
  'syms': {'flcore.core': {'flcore.core.foo': ('core.html#foo', 'flcore/core.py')}}}
